### PR TITLE
fix: typescript support

### LINKED ISSUE #910: TypeScript won't run
### Expected Behavior

1. Download Elide at `alpha9`
2. Write some TypeScript to a file
3. Run `elide test.ts`
4. It runs

### Actual Behaviour

1. Download Elide at `alpha9`
2. Write some TypeScript to a file
3. Run `elide test.ts`
4. It crashes

### Stacktrace

```
java.lang.IllegalArgumentException: A language with id 'typescript' is not installed. Installed languages are: [llvm, python, ruby, js, ts, wasm].
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.throwNotInstalled(PolyglotEngineImpl.java:1168)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(PolyglotEngineImpl.java:1175)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(PolyglotContextImpl.java:1700)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.lookupLanguageContext(PolyglotContextImpl.java:1662)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.parse(PolyglotContextImpl.java:1643)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.parse(PolyglotContextDispatch.java:65)
	at org.graalvm.polyglot/org.graalvm.polyglot.Context.parse(Context.java:483)
	at elide.runtime.core.internals.graalvm.GraalVMContext.parse(GraalVMContext.kt:42)
	at elide.tool.cli.cmd.repl.ToolShellCommand.readExecuteCode(ToolShellCommand.kt:1515)
	at elide.tool.cli.cmd.repl.ToolShellCommand.invoke$lambda$58(ToolShellCommand.kt:1862)
	at elide.tool.cli.AbstractSubcommand.withContext(AbstractSubcommand.kt:540)
	at elide.tool.cli.cmd.repl.ToolShellCommand.invoke(ToolShellCommand.kt:1808)
	at elide.tool.cli.cmd.repl.ToolShellCommand$invoke$1.invokeSuspend(ToolShellCommand.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at elide.tool.cli.AbstractToolCommand.execute(AbstractToolCommand.kt:129)
	at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:153)
	at elide.tool.cli.ElideTool.invoke-AZeniH0(ElideTool.kt:273)
	at elide.tool.cli.AbstractToolCommand$call$1.invokeSuspend(AbstractToolCommand.kt:154)
	at elide.tool.cli.AbstractToolCommand$call$1.invoke-AZeniH0(AbstractToolCommand.kt)
	at elide.tool.cli.AbstractToolCommand$call$1.invoke(AbstractToolCommand.kt)
	at elide.tool.cli.AbstractToolCommand$execute$6.invokeSuspend(AbstractToolCommand.kt:130)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at elide.tool.cli.AbstractToolCommand.execute(AbstractToolCommand.kt:129)
	at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:153)
	at elide.tool.cli.AbstractToolCommand.run(AbstractToolCommand.kt:164)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at elide.tool.cli.ElideTool$Companion.exec$cli(ElideTool.kt:189)
	at elide.tool.cli.ElideTool$Companion.main(ElideTool.kt:160)
	at elide.tool.cli.ElideTool.main(ElideTool.kt)
```

### Steps To Reproduce

See above.

### Environment Information

- Operating System: macOS 14.x Sonoma
- Architecture: M-series (aarch64)

### Runtime

Native, JVM

### Language

JavaScript

### Example Application

_No response_

### Version

1.0.0-alpha9

### PR DESCRIPTION
**Pull request by sgammon**
Ready for review [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=elide-dev&utm_campaign=badge_info)

## Summary

Fixes TypeScript support from the entrypoint; fixes the TypeScript module patcher which allows for TypeScript-native imports.

- Fixes #910 
- Relates to #824 

## Changelog

- fix: typescript compiler and js realm/context use
- fix: invocation of typescript from entrypoint
- fix: module loader requires access to disk

### CODE REVIEW

File: packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/sqlite/SqliteModule.kt [hunk 1]
```diff
@@ -94,13 +94,7 @@ internal class SqliteModule : SQLiteAPI {
...
 
     init {
-      // on SVM, we should load the library directly using our own tools; this is because sqlite3 may be built into the
-      // binary statically, and loaded via our own facilities at build-time.
-      if (ImageInfo.inImageCode()) NativeLibraries.resolve(SQLITE3_LIBRARY) {
-        org.sqlite.SQLiteJDBCLoader.initialize()
-      } else {
-        // otherwise, on JVM, we should load the library through regular SQLite3 JDBC mechanisms; this will unpack the
-        // library to a temporary location, load it, and then clean up after itself.
+      NativeLibraries.resolve(SQLITE3_LIBRARY) {
```
Comment (darvld) [inline packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/sqlite/SqliteModule.kt:97]: Is this change meant to be part of this PR? Seems related to SQLite instead.

**Review by darvld — APPROVED** [review]
Looks good, just a comment

File: packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/sqlite/SqliteModule.kt (hunk 1 above)
Comment (sgammon) [reply packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/sqlite/SqliteModule.kt:97]: Yes, it's related -- fixes for mobile libs
