### PR TITLE
fix: jna os info on linux/macos

### LINKED ISSUE #990: Cannot load JNA on `main`
### Expected Behavior

Loading features which use JNA, like `node:os`, should work

### Actual Behaviour

Causing a crash

### Stacktrace

On macOS aarch64:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 856, in exec_module
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1413, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1379, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1355, in _path_hooks
  File "<frozen zipimport>", line 76, in __init__
  File "<frozen importlib._bootstrap_external>", line 147, in _path_stat
java.lang.Integer cannot be cast to java.lang.Long
Looking for library 'System'
Adding paths from jna.library.path: null
Trying libSystem.dylib
Loading failed with message: com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
Adding system paths: [/usr/lib]
Trying libSystem.dylib
Loading failed with message: com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
Trying /Users/sam/Library/Frameworks/System.framework/System
Loading failed with message: com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
Trying /Library/Frameworks/System.framework/System
Loading failed with message: com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
Trying /System/Library/Frameworks/System.framework/System
Loading failed with message: com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@27f674d for System
Loading failed with message: Native library (darwin-aarch64/libSystem.dylib) not found in resource path ()

╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Unable to load library 'System':
com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]
Native library (darwin-aarch64/libSystem.dylib) not found in resource path ()║
╟────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Advice:                                                                                                                    ║
║ This is an error in Elide. Please report this to the Elide Team with `elide bug`                                           ║
╟────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Stacktrace:                                                                                                                ║
║                                                                                                                            ║
║ Unable to load library 'System':                                                                                           ║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ Native library (darwin-aarch64/libSystem.dylib) not found in resource path ()                                              ║
║ 	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:325)                                                     ║
║ 	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:481)                                                     ║
║ 	at com.sun.jna.Library$Handler.<init>(Library.java:197)                                                              ║
║ 	at com.sun.jna.Native.load(Native.java:618)                                                                          ║
║ 	at com.sun.jna.Native.load(Native.java:592)                                                                          ║
║ 	at com.sun.jna.platform.mac.SystemB.<clinit>(SystemB.java:40)                                                        ║
║ 	at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:52)                                                      ║
║ 	at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:40)                                                      ║
║ 	at oshi.hardware.platform.mac.MacCentralProcessor.initProcessorCounts(MacCentralProcessor.java:138)                  ║
║ 	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:68)                            ║
║ 	at oshi.hardware.platform.mac.MacCentralProcessor.<init>(MacCentralProcessor.java:51)                                ║
║ 	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.createProcessor(MacHardwareAbstractionLayer.java:42)       ║
║ 	at oshi.util.Memoizer$1.get(Memoizer.java:61)                                                                        ║
║ 	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)      ║
║ 	at elide.runtime.gvm.internals.node.os.NodeOperatingSystem$BaseOS.cpus(NodeOperatingSystem.kt:317)                   ║
║ 	at elide.runtime.gvm.internals.node.os.NodeOperatingSystem$ModuleBase.getMember$lambda$2(NodeOperatingSystem.kt:203) ║
║ 	at <js> h(../../../../__runtime__/os/os.cjs:1:1310-1319)                                                             ║
║ 	at <js> :program(tools/scripts/cpu.js:2:44-52)                                                                       ║
║ 	at org.graalvm.polyglot/org.graalvm.polyglot.Value.execute(Value.java:928)                                           ║
║ 	at elide.tool.cli.cmd.repl.ToolShellCommand.readExecuteCode(ToolShellCommand.kt:1540)                                ║
║ 	at elide.tool.cli.cmd.repl.ToolShellCommand.invoke$lambda$57(ToolShellCommand.kt:1877)                               ║
║ 	at elide.tool.cli.AbstractSubcommand.withContext(AbstractSubcommand.kt:574)                                          ║
║ 	at elide.tool.cli.cmd.repl.ToolShellCommand.invoke(ToolShellCommand.kt:1823)                                         ║
║ 	at elide.tool.cli.cmd.repl.ToolShellCommand$invoke$1.invokeSuspend(ToolShellCommand.kt)                              ║
║ 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                            ║
║ 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)                                                      ║
║ 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)                                    ║
║ 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)                                                 ║
║ 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)                                             ║
║ 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)                                                         ║
║ 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)                                     ║
║ 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)                                                 ║
║ 	at com.jakewharton.mosaic.BlockingKt.runMosaicBlocking(blocking.kt:6)                                                ║
║ 	at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:260)                                               ║
║ 	at elide.tool.cli.Elide.invoke-AZeniH0(Elide.kt:299)                                                                 ║
║ 	at elide.tool.cli.AbstractToolCommand$call$$inlined$execute$1.invokeSuspend(AbstractToolCommand.kt:155)              ║
║ 	at elide.tool.cli.AbstractToolCommand$call$$inlined$execute$1.invoke(AbstractToolCommand.kt)                         ║
║ 	at elide.tool.cli.AbstractToolCommand$call$$inlined$execute$1.invoke(AbstractToolCommand.kt)                         ║
║ 	at com.jakewharton.mosaic.MosaicKt$runMosaic$2$4.invokeSuspend(mosaic.kt:147)                                        ║
║ 	at com.jakewharton.mosaic.MosaicKt$runMosaic$2$4.invoke(mosaic.kt)                                                   ║
║ 	at com.jakewharton.mosaic.MosaicKt$runMosaic$2$4.invoke(mosaic.kt)                                                   ║
║ 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)                        ║
║ 	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)                                         ║
║ 	at com.jakewharton.mosaic.MosaicKt$runMosaic$2.invokeSuspend(mosaic.kt:124)                                          ║
║ 	at com.jakewharton.mosaic.MosaicKt$runMosaic$2.invoke(mosaic.kt)                                                     ║
║ 	at com.jakewharton.mosaic.MosaicKt$runMosaic$2.invoke(mosaic.kt)                                                     ║
║ 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)                        ║
║ 	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)                                         ║
║ 	at com.jakewharton.mosaic.MosaicKt.runMosaic(mosaic.kt:58)                                                           ║
║ 	at com.jakewharton.mosaic.BlockingKt$runMosaicBlocking$1.invokeSuspend(blocking.kt:7)                                ║
║ 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                            ║
║ 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)                                                      ║
║ 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)                                    ║
║ 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)                                                 ║
║ 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)                                             ║
║ 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)                                                         ║
║ 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)                                     ║
║ 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)                                                 ║
║ 	at com.jakewharton.mosaic.BlockingKt.runMosaicBlocking(blocking.kt:6)                                                ║
║ 	at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:260)                                               ║
║ 	at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:30)                                                ║
║ 	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)                                                      ║
║ 	at picocli.CommandLine.access$1500(CommandLine.java:148)                                                             ║
║ 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)                ║
║ 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)                                                         ║
║ 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)                                                         ║
║ 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)                                     ║
║ 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)                                                        ║
║ 	at picocli.CommandLine.execute(CommandLine.java:2174)                                                                ║
║ 	at elide.tool.cli.Elide$Companion.exec$runtime(Elide.kt:232)                                                         ║
║ 	at elide.tool.cli.Elide$Companion.entry(Elide.kt:195)                                                                ║
║ 	at elide.tool.cli.ElideKt.main(Elide.kt:305)                                                                         ║
║ Caused by host exception: java.lang.UnsatisfiedLinkError: Unable to load library 'System':                                 ║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ com.sun.jna.Native.open(Ljava/lang/String;I)J [symbol: Java_com_sun_jna_Native_open or Java_com_sun_jna_Native_open__Ljava_lang_String_2I]║
║ Native library (darwin-aarch64/libSystem.dylib) not found in resource path ()                                              ║
║                                                                                                                            ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

On Linux amd64:
```
╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Could not initialize class com.sun.jna.platform.linux.Udev                                                                    ║
╟───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Advice:                                                                                                                       ║
║ This is an error in Elide. Please report this to the Elide Team with `elide bug`                                              ║
╟───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Stacktrace:                                                                                                                   ║
║                                                                                                                               ║
║ Could not initialize class com.sun.jna.platform.linux.Udev                                                                    ║
║       at oshi.hardware.platform.linux.LinuxCentralProcessor.queryCurrentFreq(LinuxCentralProcessor.java:446)                  ║
║       at oshi.util.Memoizer$1.get(Memoizer.java:61)                                                                           ║
║       at oshi.hardware.common.AbstractCentralProcessor.getCurrentFreq(AbstractCentralProcessor.java:130)                      ║
║       at elide.runtime.gvm.internals.node.os.NodeOperatingSystem$BaseOS.cpus(NodeOperatingSystem.kt:317)                      ║
║       at elide.runtime.gvm.internals.node.os.NodeOperatingSystem$ModuleBase.getMember$lambda$2(NodeOperatingSystem.kt:203)    ║
║       at <js> h(__runtime__/os/os.cjs:1:1310-1319)                                                                            ║
║       at <js> :program(<shell:js>:1:0-24)                                                                                     ║
║       at org.graalvm.polyglot/org.graalvm.polyglot.Context.eval(Context.java:402)                                             ║
║       at elide.runtime.core.internals.graalvm.GraalVMContext.evaluate(GraalVMContext.kt:47)                                   ║
║       at elide.tool.cli.cmd.repl.ToolShellCommand.executeOneChunk(ToolShellCommand.kt:833)                                    ║
║       at elide.tool.cli.cmd.repl.ToolShellCommand.beginInteractiveSession$lambda$22$lambda$21(ToolShellCommand.kt:1375)       ║
║       at elide.tool.cli.cmd.repl.ToolShellCommand.initCLI(ToolShellCommand.kt:976)                                            ║
║       at elide.tool.cli.cmd.repl.ToolShellCommand.beginInteractiveSession(ToolShellCommand.kt:1359)                           ║
║       at elide.tool.cli.cmd.repl.ToolShellCommand.invoke$lambda$57(ToolShellCommand.kt:1871)                                  ║
║       at elide.tool.cli.AbstractSubcommand.withContext(AbstractSubcommand.kt:574)                                             ║
║       at elide.tool.cli.cmd.repl.ToolShellCommand.invoke(ToolShellCommand.kt:1842)                                            ║
║       at elide.tool.cli.cmd.repl.ToolShellCommand$invoke$1.invokeSuspend(ToolShellCommand.kt)                                 ║
║       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                               ║
║       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)                                                         ║
║       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)                                       ║
║       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)                                                    ║
║       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)                                                ║
║       at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)                                                            ║
║       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)                                        ║
║       at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)                                                    ║
║       at com.jakewharton.mosaic.BlockingKt.runMosaicBlocking(blocking.kt:6)                                                   ║
║       at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:260)                                                  ║
║       at elide.tool.cli.Elide.invoke-AZeniH0(Elide.kt:299)                                                                    ║
║       at elide.tool.cli.AbstractToolCommand$call$$inlined$execute$1.invokeSuspend(AbstractToolCommand.kt:155)                 ║
║       at elide.tool.cli.AbstractToolCommand$call$$inlined$execute$1.invoke(AbstractToolCommand.kt)                            ║
║       at elide.tool.cli.AbstractToolCommand$call$$inlined$execute$1.invoke(AbstractToolCommand.kt)                            ║
║       at com.jakewharton.mosaic.MosaicKt$runMosaic$2$4.invokeSuspend(mosaic.kt:147)                                           ║
║       at com.jakewharton.mosaic.MosaicKt$runMosaic$2$4.invoke(mosaic.kt)                                                      ║
║       at com.jakewharton.mosaic.MosaicKt$runMosaic$2$4.invoke(mosaic.kt)                                                      ║
║       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)                           ║
║       at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)                                            ║
║       at com.jakewharton.mosaic.MosaicKt$runMosaic$2.invokeSuspend(mosaic.kt:124)                                             ║
║       at com.jakewharton.mosaic.MosaicKt$runMosaic$2.invoke(mosaic.kt)                                                        ║
║       at com.jakewharton.mosaic.MosaicKt$runMosaic$2.invoke(mosaic.kt)                                                        ║
║       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)                           ║
║       at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)                                            ║
║       at com.jakewharton.mosaic.MosaicKt.runMosaic(mosaic.kt:58)                                                              ║
║       at com.jakewharton.mosaic.BlockingKt$runMosaicBlocking$1.invokeSuspend(blocking.kt:7)                                   ║
║       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                               ║
║       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)                                                         ║
║       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)                                       ║
║       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)                                                    ║
║       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)                                                ║
║       at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)                                                            ║
║       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)                                        ║
║       at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)                                                    ║
║       at com.jakewharton.mosaic.BlockingKt.runMosaicBlocking(blocking.kt:6)                                                   ║
║       at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:260)                                                  ║
║       at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:30)                                                   ║
║       at picocli.CommandLine.executeUserObject(CommandLine.java:2045)                                                         ║
║       at picocli.CommandLine.access$1500(CommandLine.java:148)                                                                ║
║       at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)                   ║
║       at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)                                                            ║
║       at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)                                                            ║
║       at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)                                        ║
║       at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)                                                           ║
║       at picocli.CommandLine.execute(CommandLine.java:2174)                                                                   ║
║       at elide.tool.cli.Elide$Companion.exec$runtime(Elide.kt:232)                                                            ║
║       at elide.tool.cli.Elide$Companion.entry(Elide.kt:195)                                                                   ║
║       at elide.tool.cli.ElideKt.main(Elide.kt:305)                                                                            ║
║ Caused by host exception: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.linux.Udev          ║
║                                                                                                                               ║
╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

### Steps To Reproduce

1. Clone `main`
2. `./gradlew :packages:runtime:nativeCompile`
3. `./packages/runtime/build/native/nativeCompile/elide.debug ./tools/scripts/cpu.js`

Contents of `cpu.js`:
```javascript
const os = require("node:os");
const cpus = os.cpus();
console.log("CPU info: " + JSON.stringify(cpus, null, 2))
```

### Environment Information

- Operating System(s): macOS 14.4.1 / Ubuntu Linux 22.04.3 LTS (Jammy)
- Architecture(s): aarch64 / AMD64

### Runtime

Native

### Language

N/A (Default)

### Example Application

_No response_

### Version

`main`

### PR DESCRIPTION
**Pull request by sgammon**
Ready for review [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=elide-dev&utm_campaign=badge_info)

## Summary

Builds on top of #988 with a better suite of fixes on both macOS and Linux for OS info obtain via OSHI/JNA. Fixes and closes #990.

- [x] Fixes on macOS
- [x] Fixes on Linux

## Changelog

- fix: jna/oshi reflection and proxy metadata
- fix: no stacktrace for host-side error causes in native mode
- chore: cpu test script
- chore: update `graalvm` module pin / detekt baseline

### CODE REVIEW

File: packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/AbstractStaticNativeLibraryFeature.kt [hunk 1]
```diff
@@ -171,7 +171,9 @@ public abstract class AbstractStaticNativeLibraryFeature : NativeLibraryFeature
       if (it.registerJni) (access as BeforeAnalysisAccessImpl).nativeLibraries.let { nativeLibraries ->
         when (it.type) {
           STATIC -> nativeLibraries.addStaticJniLibrary(it.name)
-          SHARED -> error("Dynamic native libraries not supported yet: $it")
+          SHARED -> if (it.registerJni) { /* Dynamic JNI libraries use JNI to load. */ } else {
+            nativeLibraries.addDynamicNonJniLibrary(it.name)
+          }
```
Comment (darvld) [inline packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/AbstractStaticNativeLibraryFeature.kt:176]: Is there a point to having the empty `if` branch? why not invert the condition and keep the comment?

Comment (sgammon) [reply packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/AbstractStaticNativeLibraryFeature.kt:176]: @darvld good point -- should get compiled out since `it.registerJni` is known at compile time (this is all build time code anyway) but will catch in the next PR. there is going to be logic in that other branch eventually, i think

**Review by darvld — APPROVED** [review]
Approved with small comments 👍

File: packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/AbstractStaticNativeLibraryFeature.kt (hunk 1 above)
Comment (darvld) [reply packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/AbstractStaticNativeLibraryFeature.kt:176]: I agree that the compiler will optimize it out, I was just checking if you had forgotten to add some logic there 👍
